# Generated by Django 4.2.26 on 2025-11-19 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('curso', models.CharField(choices=[('infantil', 'Infantil'), ('primaria', 'Primaria')], max_length=20)),
                ('tags', models.CharField(max_length=200)),
                ('json', models.CharField(max_length=2000)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='actividades/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
